install:
  - sudo apt-get update
  - sudo apt-get install debootstrap 
  - sudo apt-get install schroot
  - sudo mkdir -p /newmount
  - sudo debootstrap --variant=buildd trusty /newmount http://archive.ubuntu.com/ubuntu/
  - sudo mount -o bind /proc /newmount/proc
  - sudo cp /etc/resolv.conf /newmount/etc/resolv.conf
  - sudo chroot /newmount apt-get install sudo&&sudo apt-get update&&sudo apt-get install virtualbox&&echo hi
  - sudo chroot /newmount mkdir /go
  - sudo chroot /newmount export GOPATH=/go
  - sudo chroot /newmount sudo apt-get install golang
  - sudo chroot /newmount sudo go get github.com/boot2docker/boot2docker-cli
  - sudo chroot /newmount cd $GOPATH/src/github.com/boot2docker/boot2docker-cli&&make goinstall
  - sudo chroot /newmount $GOPATH/bin/boot2docker-cli init -v
  - sudo chroot /newmount $GOPATH/bin/boot2docker-cli up
  - ls 
script:
  - echo hello world
