install:
  - sudo apt-get update
  - sudo apt-get install virtualbox
  - sudo apt-get install dkms
  - sudo apt-get install virtualbox-ose-dkms
  - virtualbox -version
  #other stuff
  - go get github.com/boot2docker/boot2docker-cli
  - cd $GOPATH/src/github.com/boot2docker/boot2docker-cli
  - make goinstall
  - sudo $GOPATH/bin/boot2docker-cli init -v
  - sudo $GOPATH/bin/boot2docker-cli up
  - ls 
script:
  - echo hello world
