install:
  - sudo apt-get update
  - sudo apt-get install virtualbox
  - go get github.com/boot2docker/boot2docker-cli
  - cd $GOPATH/src/github.com/boot2docker/boot2docker-cli
  - make goinstall
  - $GOPATH/bin/boot2docker-cli init
  - $GOPATH/bin/boot2docker-cli up
  - ls 
script:
  - echo hello world
