install:
  - sudo apt-get update
  - sudo wget http://download.virtualbox.org/virtualbox/4.3.12/virtualbox-4.3_4.3.12-93733~Ubuntu~lucid_i386.deb
  - sudo dpkg -i virtualbox-4.3_4.3.12-93733~Ubuntu~lucid_i386.deb
  - go get github.com/boot2docker/boot2docker-cli
  - cd $GOPATH/src/github.com/boot2docker/boot2docker-cli
  - make goinstall
  - sudo $GOPATH/bin/boot2docker-cli init
  - sudo $GOPATH/bin/boot2docker-cli up
  - ls 
script:
  - echo hello world
