install:
  - sudo apt-get update
  - sudo apt-get install debootstrap 
  - sudo apt-get install schroot
  - sudo mkdir -p /newmount
  - sudo debootstrap --variant=buildd trusty /newmount http://archive.ubuntu.com/ubuntu/
  - sudo chroot /newmount apt-get install virtualbox&&echo hi
  - ls 
script:
  - echo hello world
