install:
  - sudo apt-get update
  - sudo apt-get install virtualbox
  #other stuff
  - sudo modprobe vboxdrv
  - go get github.com/boot2docker/boot2docker-cli
  - cd $GOPATH/src/github.com/boot2docker/boot2docker-cli
  - make goinstall
  - sudo $GOPATH/bin/boot2docker-cli init -v
  - sudo $GOPATH/bin/boot2docker-cli up
  - ls 
script:
  - echo hello world
